#!/usr/bin/env node
// Reference generator for the docs-as-code site (docs-site spec, Phase 2 / K8).
//
// Produces the GENERATED technical-appendix pages under
// `apps/docs/src/content/docs/reference/` from their single canonical sources —
// so the reference can never silently drift from the code it describes. The
// companion `scripts/check-docs.mjs` regenerates and diffs in CI to enforce it.
//
// Source-of-truth & ordering (K8): this reads the BUILT packages
// (`@librarian/mcp-server`, the CLI dist) rather than re-parsing TypeScript, so
// `pnpm build` must run before `pnpm docs:gen` / `pnpm check:docs`. CI wires the
// check AFTER the build step so it can never pass against stale output.
//
// Run `pnpm docs:gen` to (re)write the pages; commit the result.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { tools } from "@librarian/mcp-server";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const referenceDir = path.join(repoRoot, "apps/docs/src/content/docs/reference");

// Fields the server fills in from the caller's authenticated token. They appear
// in a tool's input schema but are never passed by an agent — the reference
// must say so rather than present them as ordinary parameters (Jim's call).
const SERVER_POPULATED = new Set(["agent_id"]);

/** A `<!-- … -->` banner stamped onto every generated page. */
function generatedBanner(source) {
  return (
    `<!-- GENERATED by scripts/docs-gen.mjs from ${source}. ` +
    `Do not edit by hand — run \`pnpm docs:gen\` to update. -->`
  );
}

/** Render a JSON-Schema property's type as a short, human label. */
function renderType(prop) {
  const raw = prop?.type;
  // `["string", "null"]` unions model an optional/omittable field — show the
  // meaningful (non-null) member.
  const base = Array.isArray(raw) ? (raw.find((t) => t !== "null") ?? raw[0]) : raw;
  if (base === "array") {
    const itemType = prop?.items?.type;
    return itemType ? `${itemType}[]` : "array";
  }
  return base ?? "unknown";
}

/** required | optional | server-populated, for the parameter table. */
function renderRequiredness(name, schema) {
  if (SERVER_POPULATED.has(name)) return "server-populated";
  const required = Array.isArray(schema.required) ? schema.required : [];
  return required.includes(name) ? "required" : "optional";
}

/** The Markdown section for a single MCP verb. */
function renderVerbSection(tool) {
  const schema = tool.inputSchema ?? {};
  const properties = schema.properties ?? {};
  const lines = [`## \`${tool.name}\``, "", tool.description, ""];

  const names = Object.keys(properties);
  if (names.length === 0) {
    lines.push("_Takes no parameters._", "");
    return lines.join("\n");
  }

  lines.push("| Parameter | Type | Required | Description |");
  lines.push("| --- | --- | --- | --- |");
  for (const name of names) {
    const prop = properties[name];
    lines.push(
      `| \`${name}\` | \`${renderType(prop)}\` | ${renderRequiredness(name, schema)} | ${prop.description} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** The full `reference/mcp-verbs.md` page. */
export function renderMcpVerbs(toolList) {
  const header = [
    "---",
    "title: MCP verbs",
    "description: The seven memory and handoff verbs the server exposes to connected agents.",
    "---",
    "",
    generatedBanner("packages/mcp-server/src/mcp/tools/"),
    "",
    "These are the seven verbs the MCP server advertises to every connected agent.",
    "Each verb's description below is the exact text an agent receives at call time.",
    "Parameters marked **server-populated** are resolved from your authenticated token —",
    "you never pass them.",
    "",
  ].join("\n");

  const sections = toolList.map(renderVerbSection).join("\n");
  return `${header}\n${sections}`;
}

/** Map of repo-relative output path → file contents. The single place that
 *  enumerates what the reference comprises; `check-docs.mjs` consumes it too. */
export function generateReference() {
  return {
    "apps/docs/src/content/docs/reference/mcp-verbs.md": renderMcpVerbs(tools),
  };
}

function writeAll() {
  fs.mkdirSync(referenceDir, { recursive: true });
  const files = generateReference();
  for (const [relPath, contents] of Object.entries(files)) {
    const abs = path.join(repoRoot, relPath);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    // Trailing newline so the file is POSIX-clean and prettier-stable.
    fs.writeFileSync(abs, contents.endsWith("\n") ? contents : `${contents}\n`);
    console.log(`docs:gen wrote ${relPath}`);
  }
}

// Only write files when run directly (`pnpm docs:gen`); importing the render
// functions (the parity test, check-docs.mjs) must have no side effects.
if (import.meta.url === `file://${process.argv[1]}`) {
  writeAll();
}
